<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationIcon>Assets/Icons/vodbox.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/Icons/linux/256/vodbox.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VodBox.Core\VodBox.Core.csproj" />
    <ProjectReference Include="..\VodBox.Infrastructure\VodBox.Infrastructure.csproj" />
    <ProjectReference Include="..\VodBox.Playback.Mpv\VodBox.Playback.Mpv.csproj" />
  </ItemGroup>
</Project>
