<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AllowUnsafeBlocks>true</AllowUnsafeBlocks><OptimizationPreference>Speed</OptimizationPreference></PropertyGroup><PropertyGroup Condition="'$(RuntimeIdentifier)' != '' and '$(Configuration)' == 'Release' and '$(DisableAOT)' != 'true'">
    <PublishAot>true</PublishAot><PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../VodBox.Core/VodBox.Core.csproj" /></ItemGroup></Project>
