<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TrimMode>full</TrimMode></PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' and '$(Configuration)' == 'Release' and '$(DisableAOT)' != 'true'">
    <PublishAot>true</PublishAot><PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/VodBox.Desktop/VodBox.Desktop.csproj" AdditionalProperties="PublishAot=true" Condition="'$(Configuration)' == 'Release' and '$(RuntimeIdentifier)' != '' and '$(DisableAOT)' != 'true'" />
    <ProjectReference Include="../../src/VodBox.Desktop/VodBox.Desktop.csproj" Condition="'$(Configuration)' != 'Release' or '$(RuntimeIdentifier)' == '' or '$(DisableAOT)' == 'true'" />
  </ItemGroup>
</Project>
