<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><PublishAot Condition="'$(RuntimeIdentifier)' != ''">true</PublishAot><PublishTrimmed Condition="'$(RuntimeIdentifier)' != ''">true</PublishTrimmed><TrimMode>full</TrimMode></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/VodBox.Playback.Mpv/VodBox.Playback.Mpv.csproj" /></ItemGroup>
</Project>
